version: '3.1'

services:
  db:
    image: postgres:10.4
    container_name: db
    environment:
      POSTGRES_PASSWORD: '${SECRET_DB}'
      POSTGRES_USER: staging_db_user
      POSTGRES_DB: staging_db
    volumes:
      - staging_db:/var/lib/postgresql/data
  static:
    image: nginx_static_staging
    container_name: static
  proxy:
    image: nginx_proxy_staging
    container_name: proxy
    volumes:
      - letsencrypt:/etc/letsencrypt/:ro
    ports:
        - 80:80
        - 443:443
    depends_on:
      - web
      - static
  web:
    image: django_staging
    container_name: web
    depends_on:
      - db
    environment:
      - SECRET_KEY
      - SECRET_DB
volumes:
  staging_db:
  letsencrypt:
