version: '3.7'

services:
  db:
    image: postgres:11.4-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: '${SECRET_DB}'
      POSTGRES_USER: web-user
      POSTGRES_DB: web-db
    volumes:
      - db-web:/var/lib/postgresql/data
  proxy:
    image: nginx-prod
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      -web 
  web:
    image: django-prod
    container_name: web 
    depends_on:
      - db
    environment:
      - SECRET_KEY
      - SECRET_DB
volumes:
  db-web:

